### PR TITLE
remove testing requirement for node v8

### PR DESCRIPTION
**Pull request by aaronfay**
Remove v8 as a testing requirement

### CODE REVIEW

**Comment by justinklemm** [comment]
@aaronfay Can we add v14 while we're at it?

**Review by justinklemm — DISMISSED** [review]

**Comment by aaronfay** [comment]
@justinklemm would it be worth making those Travis checks mandatory as well? 👇🏻

**Comment by justinklemm** [comment]
I actually think TravisCI is being kill or become paid-only or something anyway, so I'm not sure we should. We're only using it because Azure made us, right?

Screen Shot 2021-03-15 at 11 27 00 AM

**Review by justinklemm — APPROVED** [review]

**Comment by aaronfay** [comment]
I've removed the Travis config (as discussed) and dropped the status badge for now.

**Pull request merged**
