### PR TITLE
Circle config

### PR DESCRIPTION
**Pull request by aaronfay**
Reverts `1.0.2`, remove build status badge from VSM public page: https://docs.microsoft.com/en-us/vsts/extend/develop/manifest#approvedbadges

### CODE REVIEW

**Comment by aaronfay** [comment]
@justinklemm the `1.0.2` -> `1.0.1` is in there, just not showing in the PR for some reason...

**Comment by aaronfay** [comment]
Yeah I thought about that too. I think it would be worth it - to me little green badge is credibility. I'll circle back around in a bit and set it up. Do we have a travis account already?

**Comment by justinklemm** [comment]
Can you get to this? https://travis-ci.org/ghost-inspector/ghost-inspector-vsts-extension

**Comment by aaronfay** [comment]
Yes, thanks!

**Pull request merged**
